export const Routes = {
  HOME: 'HOME' as 'HOME',
  LOGIN: 'LOGIN' as 'LOGIN',
  TRANSACTION_HISTORY: 'TRANSACTION_HISTORY' as 'TRANSACTION_HISTORY',
  BIOMETRIC_ENABLE: 'BIOMETRIC_ENABLE' as 'BIOMETRIC_ENABLE',
  TRANSACTION_DETAILS: 'TRANSACTION_DETAILS' as 'TRANSACTION_DETAILS',
};
